# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FprK19YIQLyH636Q/wSH46j+kzgWNJU1JVDk4k8H4qNcUcmMCMNzE2GTUpBNxXbXNVGdlBOQGb2OvTPdXYqKOxTWOASrcpOgYEigwcshhrJDrq0yT3JB2k4ADqHG7BEvf5oi/B32rP9pfN1zzxe8VU8hXbeRujOgmL9YLwKWV1JFv+x1ONmLw3S6vUwIcaj0K2qsMIavS0K7/vt+phRoSSwlP6avwzSD7q/79JfKgd8hpOzvxVqWja57SCVfHtkrMXNHZ5VSVvRBdBRq4VXF+wVc3AIyVCR88Uwcg7TKBhu6gNMwyQaPpSQgPTZ1Y3JpNi/EmLUJBtPnk4IcO7kAoi5Oas+CcfDI5gX/z+rDL2anFe1ESWpeSJz5KkJOZ2Gdxtwcmmd12RT8bE2C9exy47bbtjHk/wsiQVt97nQhOK0E5QQiqkeqtfzntSxK3O1js1VjW+oyV2huT9ANgQ4udC9a0O44iLqSxiiV/SA07hiYnrDdoRIg5T4v1PmiOoS2agwGRlzISyt+VEgJX76mje9sWt7D5Qn0OktEIa0iOkH8cqob52Xv6PLHezeyNWz03gl7hB3qqnLdfmGEvEJ0++G17AhqvFY88bwXBOCM1iSCuJ+6hchgh+CZqLTkLthZ1UFikEOSnNMdu2weTFRQFr31hY2Tc2jeMz/DxkBN8k4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
