appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FprK19YIQLyH636Q/wSH46j+kzgWNJU1JVDk4k8H4qNcUcmMCMNzE2GTUpBNxXbXNVGdlBOQGb2OvTPdXYqKOxTWOASrcpOgYEigwcshhrJDrq0yT3JB2k4ADqHG7BEvf5oi/B32rP9pfN1zzxe8VU8hXbeRujOgmL9YLwKWV1JFv+x1ONmLw3S6vUwIcaj0K2qsMIavS0K7/vt+phRoSSwlP6avwzSD7q/79JfKgd8hpOzvxVqWja57SCVfHtkrMXNHZ5VSVvRBdBRq4VXF+wVc3AIyVCR88Uwcg7TKBhu6gNMwyQaPpSQgPTZ1Y3JpNi/EmLUJBtPnk4IcO7kAoi5Oas+CcfDI5gX/z+rDL2anFe1ESWpeSJz5KkJOZ2Gdxtwcmmd12RT8bE2C9exy47bbtjHk/wsiQVt97nQhOK0E5QQiqkeqtfzntSxK3O1js1VjW+oyV2huT9ANgQ4udC9a0O44iLqSxiiV/SA07hiYnrDdoRIg5T4v1PmiOoS2agwGRlzISyt+VEgJX76mje9sWt7D5Qn0OktEIa0iOkH8cqob52Xv6PLHezeyNWz03gl7hB3qqnLdfmGEvEJ0++G17AhqvFY88bwXBOCM1iSCuJ+6hchgh+CZqLTkLthZ1UFikEOSnNMdu2weTFRQFr31hY2Tc2jeMz/DxkBN8k4=
conda_forge_output_validation: true
